name: recupera

services:
  pg:
    image: postgres:11-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abacaxi01 
      POSTGRES_DB: recupera
    ports:
      - "5432:5432"

  recupera_app:
    image: recupera_app
    build: .
    ports:
      - "8001:8001"
    depends_on:
      - pg
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:abacaxi01@pg:5432/recupera

volumes:
  pgdata:
