"""remove cpf

Revision ID: 0006e1e1eeb7
Revises: 88f3d401d7e1
Create Date: 2025-02-18 13:03:25.952737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006e1e1eeb7'
down_revision: Union[str, None] = '88f3d401d7e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_cpf_key', 'users', type_='unique')
    op.drop_column('users', 'cpf')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cpf', sa.VARCHAR(length=14), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_cpf_key', 'users', ['cpf'])
    # ### end Alembic commands ###
