"""att 2

Revision ID: 88f3d401d7e1
Revises: 9e093089a5ae
Create Date: 2025-02-18 13:01:04.666938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88f3d401d7e1'
down_revision: Union[str, None] = '9e093089a5ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'cpf',
               existing_type=sa.VARCHAR(length=14),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'cpf',
               existing_type=sa.VARCHAR(length=14),
               nullable=True)
    # ### end Alembic commands ###
