"""att

Revision ID: 9e093089a5ae
Revises: 4b9643d1c9cb
Create Date: 2025-02-18 10:53:56.718123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e093089a5ae'
down_revision: Union[str, None] = '4b9643d1c9cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'cpf',
               existing_type=sa.VARCHAR(length=14),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'cpf',
               existing_type=sa.VARCHAR(length=14),
               nullable=False)
    # ### end Alembic commands ###
